### ISSUE TITLE
make Kimage error

### ISSUE THREAD

**Issue by informer2016** [AxFab/kora-kernel#2]
Good day, @AxFab ! I tried to build Kora to see if it could fit in a virtual floppy _( even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_ However, I got this build problem:
```
...
many lines (where everything seemed to be OK)
...
    CC  ~/kora-kernel/obj/krn/src/libc/heap.o
In file included from ~/kora-kernel/src/libc/heap.c:23:0:
~/kora-kernel/src/libc/heap.c: In function ‘valloc’:
~/kora-kernel/src/libc/heap.c:65:41: error: ‘PAGE_SIZE’ undeclared (first use in this function); did you mean ‘_T_SIZE’?
     void *map = heap_map(ALIGN_UP(size, PAGE_SIZE));

~/kora-kernel/include/kora/mcrs.h:35:35: note: in definition of macro ‘ALIGN_UP’
 #define ALIGN_UP(v,a)      (((v)+(a-1))&(~(a-1)))
                                   ^
~/kora-kernel/src/libc/heap.c:65:41: note: each undeclared identifier is reported only once for each function it appears in
     void *map = heap_map(ALIGN_UP(size, PAGE_SIZE));
                                         ^
~/kora-kernel/include/kora/mcrs.h:35:35: note: in definition of macro ‘ALIGN_UP’
 #define ALIGN_UP(v,a)      (((v)+(a-1))&(~(a-1)))
                                   ^
~/kora-kernel/src/libc/heap.c: In function ‘pvalloc’:
~/kora-kernel/src/libc/heap.c:81:40: error: ‘PAGE_SIZE’ undeclared (first use in this function); did you mean ‘_T_SIZE’?
     return _PRT(valloc)(ALIGN_UP(size, PAGE_SIZE));
                                        ^
~/kora-kernel/include/kora/mcrs.h:35:35: note: in definition of macro ‘ALIGN_UP’
 #define ALIGN_UP(v,a)      (((v)+(a-1))&(~(a-1)))
                                   ^
~/kora-kernel/src/libc/heap.c:82:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
~/kora-kernel/sources.mk:42: recipe for target '~/kora-kernel/obj/krn/src/libc/heap.o' failed
make: *** [~/kora-kernel/obj/krn/src/libc/heap.o] Error 1
```
Any ideas what I can do to fix it?

**Comment by AxFab** [comment]
Hi, 
Thank you so much for your interest on my project.

I don't have floppy support, and to be honest, it's not my first priority. However if you wanna contribute you're more than welcome to do so.
But the issue you're having troubles me! I would like to know how you are building the kernel ? What is the command you launch, and what is the value of the env vars `target` and `CROSS` before make is called ?

Because the kernel provide most of required headers an undefined symbols is unlikely.
If I have to guess, I will say you probably didn't set the `target` variable correcty and run on 64bits linux ?
I don't have support for x86_64 yet, you might wanna build for 32bits.
CI jobs use a precompiled version of them using the `scripts/toolchain.sh` to download the correct precompiled binaries (32bits target for 64bits host pc).

Please tell me if that resolves your issue.

**Comment by AxFab** [comment]
I looked at coreboot documentation, it does sound quite interesting ;)

**Comment by informer2016** [comment]
@AxFab yes, I'm trying to build Kora under x86_64 Linux, but I am a bit stuck there and don't know to what values I should set `target` and `CROSS` _( [README.md](https://github.com/AxFab/kora-kernel/blob/develop/README.md) doesn't say anything about it )_ Perhaps it would be easier to just get and launch some x86 Linux LiveCD, although many distros are ending x86 support. By the way, should I run `scripts/toolchain.sh` separately? _(when I do that - nothing happens)_

**Comment by informer2016** [comment]
@AxFab I'm happy you found coreboot BIOS interesting, and if you have any coreboot-related questions I'll try my best to give a great reply :wink: I'm using AMD A10-5750M quadcore Lenovo G505S laptop with 16GB RAM and as you see there are some of quite modern laptops/PCs among the [coreboot-supported](https://coreboot.org/status/board-status.html) list, even servers - e.g. ASUS KGPE-D16 with two AMD Opterons. Personally I prefer AMD-based ones because they don't have Intel ME hardware backdoor inside and also - while being powerful - are old enough not to have AMD PSP backdoor which _(compared to ME)_ got added much later, so the latest "AMD-without-PSP" is significantly more powerful than "Intel-without-ME"
**P.S.** By itself Lenovo G505S is really affordable, possible to get for ~$100-$150 in good condition _(although the RAM is expensive nowadays and 16GB of DDR3 cost almost the same as this laptop :stuck_out_tongue_winking_eye: )_ Just need to make sure that it has A10-5750M CPU : there were some versions with lower performance A8 or A6, and although the CPU is socket'ed and not soldered, it is about $50 to get it separately

**Comment by AxFab** [comment]
There is two lines about it on the readme, but I agree it's a bit short. I will add a small paragraphe about it ;p

By default `Makefile` is building the target and host triplet as : `$(uname -m)-pc-linux-gnu` so in your case `target=x86_64-pc-linux-gnu`. It's good as once I will support 64 bits what you want is the kernel for your platform.

However I'm not there yet, so you should cross-build using `target=x86-pc-kora`
( I have a support for `arm-raspi2-kora` on a branch, but it's still just saying "Hello world").

The `CROSS` variable is used to add a prefix to select a cross-compiler. For example if you wanna use `i386-elf-gcc` commands then you must set `CROSS=i386-elf-`

On the makefile you have:
```
CC:=gcc
LD:=ld
CC=$(CROSS)$(CC)
LD=$(CROSS)$(LD)
```

For downloading the pre-compiled toolchains : `scripts/toolchain.sh install`. Then you will have gcc on `kora-kernel/opt/bin` folder, add this one to the `PATH` to use it.

**Comment by informer2016** [comment]
@AxFab Thank you very much for these additional instructions; to be honest I got a bit stuck there and when I tried `scripts/toolchain.sh install` it simply froze for some reason, without any debug info on the screen. Perhaps I'll get some x86 Linux LiveCD and see if I could build it there, I'll keep you posted

**Comment by AxFab** [comment]
I'm closing this issue as the build script evolved a lot since.

To know more about build:
https://github.com/AxFab/koraos/wiki/Build-KoraOS
